language: c

sudo: required

os:
  - linux
  - osx

dist: trusty # Ubuntu 14.04.

compiler:
  - clang
  - gcc

env:
  - DEBUG=0 MPI=0 SHARED=0
  - DEBUG=0 MPI=0 SHARED=1
  - DEBUG=0 MPI=1 SHARED=0
  - DEBUG=0 MPI=1 SHARED=1
  - DEBUG=1 MPI=0 SHARED=0
  - DEBUG=1 MPI=0 SHARED=1
  - DEBUG=1 MPI=1 SHARED=0
  - DEBUG=1 MPI=1 SHARED=1

# Currently Apple doesn't use the real gcc, even if you tell it to.
# So we exclude the gcc compiler option from Mac builds.
# In addition, there's an open issue (#19) with NetCDF file writes in 
# polymec configurations using debug=1 and shared=1, so we exclude that 
# configuration on Macs.
matrix:
  exclude:
  - os: osx
    compiler: gcc
  - os: osx
    env: DEBUG=1 MPI=0 SHARED=1
    env: DEBUG=1 MPI=1 SHARED=1

install: sh ./.travis/install-$TRAVIS_OS_NAME-deps.sh

deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY_ID
  secret_access_key: $S3_SECRET_KEY
  bucket: polymec-dev.travis-ci
  region: us-west-2
  skip_cleanup: true
  local_dir: latest
  upload-dir: polyglot-dev
  acl: public_read

script: 
  - pushd $HOME && wget https://s3-us-west-2.amazonaws.com/polymec-dev.travis-ci/polymec-dev/polymec-$TRAVIS_OS_NAME-$CC-debug%3D$DEBUG-mpi%3D$MPI-shared%3D$SHARED.tar.gz && tar xzvf polymec-$TRAVIS_OS_NAME-$CC-debug=$DEBUG-mpi=$MPI-shared=$SHARED.tar.gz && popd
  - make config polymec="$HOME/polymec-$TRAVIS_OS_NAME-$CC-debug=$DEBUG-mpi=$MPI-shared=$SHARED" && make -j4 install && make test 

after_success: 
  - mkdir -p latest 
  - tar czvf polyglot-$TRAVIS_OS_NAME-$CC-debug=$DEBUG-mpi=$MPI-shared=$SHARED.tar.gz polymec-$TRAVIS_OS_NAME-$CC-debug=$DEBUG-mpi=$MPI-shared=$SHARED/* 
  - mv polyglot-$TRAVIS_OS_NAME-$CC-debug=$DEBUG-mpi=$MPI-shared=$SHARED.tar.gz latest

after_failure: 
  - cat build/*/Testing/Temporary/LastTest.log
